Repository Michigan-State-University/cias-api, pull requests merged in 2023-06, with the labels that each got.

#12 [CIAS30-3422][CIAS30-3420] too many notifications after leaving the channel + Editing is not stopped on channel unsubscribe
  app/channels/intervention_channel.rb
  app/models/intervention.rb
  spec/channels/intervention_channel_spec.rb
Labels: RfCR

#8 [CIAS30-3415] adjust endpoint to clone to accept emails instead of user_ids
  app/controllers/v1/interventions_controller.rb
  app/models/concerns/clone.rb
  spec/jobs/clone_jobs/intervention_spec.rb
  spec/models/intervention_spec.rb
  spec/requests/v1/interventions/clone_spec.rb
Labels: approved, BLOCKED

#19 [CIAS-3341] - Regenerate audio
  app/controllers/v1/audio_controller.rb
  app/services/v1/audio/regenerate.rb
  config/routes.rb
  spec/services/v1/audio/regenerate_spec.rb
Labels: RfCR

#9 [CIAS30-3403] add default values to settings in the number question
  app/models/question/number.rb
  spec/requests/v1/questions/create_spec.rb
Labels: approved

#10 [CIAS30-3402] add new values to settings in number questions - max and min length
  db/migrate/20230605101854_update_settings_in_exisiting_number_questions.rb
  db/schema.rb
Labels: RfCR

#1 [CIAS30-3305] get access token
  .env.template
  spec/spec_helper.rb
Labels: Henry Ford integration

#27 [CIAS-3419] - Add simple intervention serializer
  app/controllers/v1/interventions_controller.rb
  app/serializers/v1/simple_intervention_serializer.rb
Labels: RfCR

#30 [CIAS-3419] - Fix cache key
  app/serializers/v1/intervention_serializer.rb
  app/serializers/v1/simple_intervention_serializer.rb
Labels: RfCR

#33 [Cias30-3417] restructure csv
  Gemfile
  Gemfile.lock
  app/models/concerns/intervention/csv/tlfb.rb
  app/models/intervention/csv/harvester.rb
  config/initializers/devise_token_auth.rb
  spec/models/intervention/csv/harvester_spec.rb
Labels: approved
