Repository Michigan-State-University/cias-api, pull requests merged in 2023-09, with the labels that each got.

#104 [CIAS30-3592][CIAS30-3594] Introduce changes to the live chat
  app/controllers/v1/live_chat/interventions/navigators_controller.rb
  app/controllers/v1/live_chat/navigators/invitations_controller.rb
  app/models/intervention.rb
  app/models/live_chat/interventions/navigator.rb
  app/serializers/v1/live_chat/interventions/live_chat_setup_serializer.rb
  db/migrate/20230824075509_add_navigators_counter_to_interventions.rb
  db/migrate/20230824084009_populate_intervention_navigators_count.rb
  db/schema.rb
  spec/rails_helper.rb
  spec/requests/v1/live_chat/interventions/navigator_invitations/confirm_spec.rb
  spec/requests/v1/live_chat/interventions/navigators/destroy_spec.rb
Labels: approved

#118 [CIAAS30-3627]fix issue with status for some type of scheduling
  app/services/v1/user_session_schedule_service.rb
  spec/services/v1/user_session_schedule_service_spec.rb
Labels: approved

#121 [CIAS30-3626] add the rake task to seed the database with correct data
  db/seeds/interventions/chart_data_seed.rb
  lib/tasks/create_mock_chart_data.rake
Labels: approved

#124 [CIAS30-3608] Take new parameters into consideration when calculating data for pie charts
  app/services/v1/chart_statistics/create.rb
  spec/services/v1/chart_statistics/create_spec.rb
Labels: approved

#120 [CIAS30-3633] add predefined user
  app/models/ability/predefined_participant.rb
  app/models/predefined_user_parameter.rb
  app/models/user.rb
  db/migrate/20230901094411_create_predefined_user_parameters.rb
  db/schema.rb
  spec/models/predefined_user_parameter_spec.rb
Labels: approved

#117 [CIAS30-3625] terminate the scheduled jobs when intervention data has been cleared
  .rubocop.yml
  app/jobs/data_clear_jobs/clear_user_data.rb
  app/jobs/session_schedule_job.rb
  app/jobs/sms_plans/send_sms_job.rb
  app/models/user_session/classic.rb
  app/services/v1/sms_plans/cancel_scheduled_smses.rb
  app/services/v1/sms_plans/schedule_sms_for_user_session.rb
  spec/factories/user_sessions.rb
  spec/jobs/session_schedule_job_spec.rb
  spec/models/user_session_spec.rb
  spec/services/v1/sms_plans/cancel_scheduled_smses_spec.rb
  spec/services/v1/sms_plans/schedule_sms_for_user_session_spec.rb
  spec/spec_helper.rb
Labels: approved

#125 [CIAS30-3653] Fix changing the type of intervention access not updating session scheduling parameters
  app/models/intervention.rb
  spec/requests/v1/interventions/update_spec.rb
Labels: approved

#133 [CIAS30-3671] Return health_clinic_id when fetching user intervention
  app/serializers/v1/user_intervention_serializer.rb
  spec/requests/v1/user_interventions/index_spec.rb
  spec/requests/v1/user_interventions/show_spec.rb
Labels: approved

#126 [CIAS30-3644] send invitations to predefined participants
  app/controllers/v1/interventions/predefined_participants_controller.rb
  app/models/predefined_user_parameter.rb
  app/serializers/v1/predefined_participant_serializer.rb
  app/services/v1/intervention/predefined_participants/create_service.rb
  app/services/v1/intervention/predefined_participants/send_invitation.rb
  app/services/v1/intervention/publish.rb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20230905090300_add_additional_fields_to_predefined_user_parameters.rb
  db/schema.rb
  spec/requests/v1/interventions/predefined_participants/create_spec.rb
  spec/requests/v1/interventions/predefined_participants/index_spec.rb
  spec/requests/v1/interventions/predefined_participants/send_invitation_spec.rb
  spec/requests/v1/interventions/predefined_participants/update_spec.rb
  spec/services/v1/intervention/predefined_participants/create_service_spec.rb
  spec/services/v1/intervention/predefined_participants/send_invitation_spec.rb
Labels: approved

#138 [CIAS30-3676] hotfix for invitation function
  Gemfile
  Gemfile.lock
  app/models/session.rb
Labels: approved, IMPORTANT

#140 [CIAS30-3675] send alerts no matter what
  app/services/v1/sms_plans/schedule_sms_for_user_session.rb
  spec/services/v1/sms_plans/schedule_sms_for_user_session_spec.rb
Labels: approved

#135 [CIAS30-3660] fix "Duplicate Here" option for invited collaborator making copy to a intervention owner
  app/jobs/clone_jobs/intervention.rb
  app/models/concerns/clone.rb
  app/models/concerns/clone/base.rb
  app/models/concerns/clone/intervention.rb
  spec/models/intervention_spec.rb
Labels: approved

#128 [CIAS30-3658] Add the ability do activate and deactivate predefined participant accounts
  app/controllers/v1/interventions/predefined_participants_controller.rb
  config/routes.rb
  spec/requests/v1/interventions/predefined_participants/destroy_spec.rb
  spec/requests/v1/interventions/predefined_participants/update_spec.rb
Labels: approved

#132 [CIAS30-3636] Delete predefined users when clearing intervention data
  app/jobs/data_clear_jobs/clear_user_data.rb
  spec/factories/interventions.rb
  spec/factories/users.rb
  spec/jobs/data_clear_jobs/clear_user_data_spec.rb
  spec/requests/v1/downloaded_reports/create_spec.rb
  spec/services/v1/generated_reports/share_to_third_party_spec.rb
Labels: approved

#134 [CIAS30-3672] Don't allow creating user session without health_clinic_id in interventions inside organization
  app/models/user_intervention.rb
  app/models/user_session.rb
  spec/models/user_intervention_spec.rb
  spec/models/user_session_spec.rb
Labels: approved

#145 [CIAS30-3701] Sidekiq 7.0 API Migration
  Gemfile
  Gemfile.lock
  config/initializers/active_job_adapter.rb
  spec/requests/v1/user_interventions/show_spec.rb
Labels: approved

#144 [CIAS30-3638] verify predefined participnats
  app/controllers/v1/interventions/predefined_participants_controller.rb
  app/services/v1/intervention/predefined_participants/verify_service.rb
  config/routes.rb
  spec/requests/v1/interventions/predefined_participants/update_spec.rb
  spec/requests/v1/interventions/predefined_participants/verify_spec.rb
  spec/services/v1/intervention/predefined_participants/verify_service_spec.rb
Labels: approved

#146 [CIAS30-3691] fix V1::UserSessionScheduleService
  app/services/v1/user_session_schedule_service.rb
  spec/services/v1/user_session_schedule_service_spec.rb
Labels: approved

#149 [CIAS30-3667] Wrong autofinish default settings on DEV: merge TEST into DEV
  app/models/user_session/classic.rb
  app/services/v1/sms_plans/schedule_sms_for_user_session.rb
  db/migrate/20230525073847_change_default_value_for_autofinish.rb
  db/schema.rb
  lib/tasks/one_time_use/update_narrator_settings.rake
  spec/models/user_session_spec.rb
  spec/requests/v1/sessions/show_spec.rb
  spec/services/v1/sms_plans/schedule_sms_for_user_session_spec.rb
Labels: approved

#139 [CIAS30-3676] issue with inviting participants by email
  app/jobs/send_fill_invitation/intervention_job.rb
  app/jobs/send_fill_invitation/session_job.rb
  app/jobs/send_fill_invitation_job.rb
  app/jobs/session_jobs/invitation.rb
  app/mailers/session_mailer.rb
  app/models/intervention.rb
  app/models/invitation.rb
  app/models/session.rb
  app/models/session_invitation.rb
  app/services/v1/chart_statistics/create.rb
  app/views/session_mailer/inform_to_an_email.html.erb
  config/locales/en.yml
  spec/jobs/send_fill_invitation/intervention_job_spec.rb
  spec/jobs/send_fill_invitation/session_job_spec.rb
  spec/jobs/send_fill_invitation_job_spec.rb
  spec/jobs/session_jobs/invitation_job_spec.rb
  spec/models/invitation_spec.rb
Labels: approved

#141 [CIAS30-3685] Make the both ends of data range in pie charts inclusive
  app/services/v1/chart_statistics/create.rb
  spec/services/v1/chart_statistics/create_spec.rb
Labels: approved

#148 [CIAS30-3678] Fix participant having no access to the session when date provided was in the past
  app/services/v1/user_session_schedule_service.rb
  spec/services/v1/user_session_schedule_service_spec.rb
Labels: approved

#152 [CIAS30-3704] 'verify' sometimes return 500
  app/controllers/v1/interventions/predefined_participants_controller.rb
  app/models/ability/predefined_participant.rb
  app/services/v1/intervention/predefined_participants/verify_service.rb
  spec/requests/v1/interventions/predefined_participants/verify_spec.rb
  spec/services/v1/intervention/predefined_participants/verify_service_spec.rb
Labels: approved

#143 [CIAS30-3682] Restore SmsPlans::SendSmsJob jobs
  lib/tasks/one_time_use/recreate_sms_jobs.rake
Labels: approved

#142 [CIAS30-3683] Restore SessionScheduleJob jobs
  lib/tasks/one_time_use/recreate_session_schedule_jobs.rake
Labels: approved

#137 [CIAS30-3681] Restore UserSessionTimeoutJob jobs
  lib/tasks/one_time_use/recreate_timeout_jobs.rake
Labels: approved

#147 [CIAS30-3698] leave only one controller to invitate participants to the intervention
  app/controllers/v1/interventions/invitations_controller.rb
  app/controllers/v1/organizations/interventions/invitations_controller.rb
  app/controllers/v1/organizations/sessions/invitations_controller.rb
  app/controllers/v1/sessions/invitations_controller.rb
  app/models/invitation.rb
  app/serializers/v1/invitation_serializer.rb
  app/services/v1/intervention/create_invitation.rb
  config/locales/en.yml
  config/routes.rb
  spec/factories/intervention_invitations.rb
  spec/models/invitation_spec.rb
  spec/requests/v1/interventions/invitations/create_spec.rb
  spec/requests/v1/interventions/invitations/destroy_spec.rb
  spec/requests/v1/interventions/invitations/index_spec.rb
  spec/requests/v1/interventions/invitations/resend_spec.rb
  spec/requests/v1/organizations/interventions/invitations/create_spec.rb
  spec/requests/v1/organizations/sessions/invitations/create_spec.rb
  spec/requests/v1/organizations/sessions/invitations/index_spec.rb
  spec/requests/v1/sessions/invitations/create_spec.rb
  spec/requests/v1/sessions/invitations/index_spec.rb
Labels: approved

#154 [CIAS30-3665] fix the possibility to invite a user with an incorrect email address
  app/models/user.rb
  spec/requests/v1/users/invitations/create_spec.rb
  spec/services/v1/users/invitations/create_spec.rb
Labels: approved

#156 [CIAS30-3714] reset cache counters for the outcome
  app/models/concerns/clone/intervention.rb
  spec/models/intervention_spec.rb
Labels: approved

#157 [CIAS30-3715] Fix the email sent to participants not showing the correct number of days
  app/jobs/data_clear_jobs/inform_and_schedule.rb
  app/mailers/intervention_mailer/clear_data_mailer.rb
  spec/jobs/data_clear_jobs/inform_and_schedule_spec.rb
Labels: RfCR

#160 [CIAS30-3689] mark all answers for the question as draft
  app/services/v1/user_sessions/previous_question_service.rb
  spec/requests/v1/user_sessions/questions/previous_spec.rb
Labels: approved

#159 [CIAS30-3713] Partial uniq index for answer
  app/services/v1/answer_service.rb
  db/migrate/20230926081202_add_uniq_index_to_answers.rb
  db/schema.rb
  spec/services/v1/intervention/publish_spec.rb
Labels: approved

#164 [CIAS30-3728][CIAS-3729] small changes related to predefined users
  app/controllers/v1/interventions/predefined_participants_controller.rb
  app/models/intervention/csv/harvester.rb
  app/models/user.rb
  app/serializers/v1/predefined_participant_serializer.rb
  app/services/v1/intervention/predefined_participants/create_service.rb
  app/services/v1/intervention/predefined_participants/update_service.rb
  db/migrate/20230927095211_add_external_id_to_predefined_users.rb
  db/schema.rb
  spec/models/intervention/csv/harvester_spec.rb
  spec/requests/v1/interventions/predefined_participants/create_spec.rb
  spec/requests/v1/interventions/predefined_participants/index_spec.rb
  spec/requests/v1/interventions/predefined_participants/update_spec.rb
Labels: approved
