Repository Michigan-State-University/cias-api, pull requests merged in 2023-08, with the labels that each got.

#66 [CIAS30-3527]added possibility to filter by MRN, add to parameters if is present
  .env.template
  app/controllers/v1/henry_ford/patient_details_controller.rb
  app/services/api/epic_on_fhir/patient_verification.rb
  app/services/v1/henry_ford/verify_service.rb
  spec/services/api/epic_on_fhir/patient_verification_spec.rb
Labels: Henry Ford integration

#73 [CIAS30-3557] Fix for the problem with incorrect search for visits
  lib/tasks/one_time_use/assign_external_id_to_clinic_location.rake
  lib/tasks/one_time_use/dump_clinic_locations.rake
Labels: Henry Ford integration

#78 [Cias30-3563] rename flag
  app/models/concerns/clone/report_template.rb
  app/models/concerns/clone/session.rb
  app/serializers/v1/report_template_serializer.rb
  db/migrate/20230808084201_rename_is_duplicated_in_report_template.rb
  db/schema.rb
  spec/models/report_template_spec.rb
Labels: RfCR

#75 [CIAS30-3407] endpoint to duplicate report
  app/controllers/v1/sessions/report_templates_controller.rb
  app/models/concerns/clone/report_template.rb
  app/models/concerns/clone/session.rb
  app/serializers/v1/report_template_serializer.rb
  config/routes.rb
  db/migrate/20230808084201_rename_is_duplicated_in_report_template.rb
  db/schema.rb
  spec/models/report_template_spec.rb
  spec/requests/v1/report_templates/duplicate_spec.rb
Labels: RfCR

#81 [CIAS30-3551] refactor the tests for deleting report logos (extract shared examples)
  spec/requests/v1/report_templates/delete_custom_logo_spec.rb
  spec/requests/v1/report_templates/delete_logo_spec.rb
  spec/support/shared_examples/deleting_attachment.rb
Labels: approved

#80 [CIAS30-3475] add questions to the filter
  app/models/session/classic.rb
  spec/requests/v1/sessions/fetch_variables_spec.rb
Labels: approved

#86 [CIAS30-3568][CIAS30-3569] fixed bug with flag and removed restriction
  app/controllers/v1/sessions/report_templates_controller.rb
  app/models/concerns/clone/report_template.rb
  spec/models/report_template_spec.rb
  spec/requests/v1/report_templates/duplicate_spec.rb
Labels: approved

#87 [CIAS30-3477] setting correct values for special question types
  app/models/user_session.rb
  app/services/v1/flow_service/next_question/branching_service.rb
  spec/services/v1/flow_service/next_question/branching_service_spec.rb
Labels: approved

#76 [CIAS30-3445] a new endpoint to reorder
  app/controllers/concerns/resource/reorder.rb
  app/controllers/v1/report_templates/sections/variants_controller.rb
  app/controllers/v1/report_templates/sections_controller.rb
  app/controllers/v1/sms_plans/variants_controller.rb
  app/models/report_template/section/variant.rb
  app/serializers/v1/report_template/section/variant_serializer.rb
  config/routes.rb
  db/migrate/20230807064042_add_position_to_report_template_section_variants.rb
  db/migrate/20230807075218_set_correct_possition_of_variants.rb
  db/schema.rb
  lib/tasks/one_time_use/assign_correct_position_to_report_template_variants.rake
  spec/requests/v1/report_templates/sections/move_spec.rb
  spec/requests/v1/report_templates/sections/variants/move_spec.rb
  spec/requests/v1/sms_plans/variants/move_spec.rb
  spec/support/shared_examples/with_collaborators.rb
Labels: approved

#71 [CIAS30-3408] ability to duplicate report template separately
  app/controllers/v1/sessions/report_templates_controller.rb
  app/models/concerns/clone/report_template.rb
  app/models/concerns/clone/session.rb
  app/models/report_template.rb
  app/serializers/v1/export/report_template_serializer.rb
  app/serializers/v1/report_template_serializer.rb
  config/routes.rb
  db/migrate/20230802073205_add_is_duplicated_flag_to_report_templates.rb
  db/migrate/20230808084201_rename_is_duplicated_in_report_template.rb
  db/migrate/20230810121137_add_new_flag_to_report_template.rb
  db/schema.rb
  spec/models/report_template_spec.rb
  spec/requests/v1/report_templates/duplicate_spec.rb
  spec/requests/v1/report_templates/update_spec.rb
Labels: approved

#90 [CIAS30-3558] the filter was adjusted to better meet customer expectations
  app/models/intervention.rb
  spec/requests/v1/interventions/index_spec.rb
Labels: approved

#88 [Cias30-3478] update CSV
  app/models/answer/third_party.rb
  app/models/question/third_party.rb
  spec/factories/questions.rb
  spec/jobs/clone_jobs/session_spec.rb
  spec/models/intervention/csv/harvester_spec.rb
  spec/requests/v1/questions/third_party/create_spec.rb
  spec/requests/v1/sessions/clone_spec.rb
Labels: approved

#79 [CIAS30-3391][CIAS30-3476] Add possibility to use report screen variable in branching
  app/models/answer/third_party.rb
  app/models/question/third_party.rb
  app/models/session/classic.rb
  app/models/user_session.rb
  app/services/v1/flow_service/next_question/branching_service.rb
  db/migrate/20230808053849_add_new_parameters_to_existing_third_party_questions.rb
  db/schema.rb
  db/schema/question/third_party/body.json
  spec/factories/questions.rb
  spec/jobs/clone_jobs/session_spec.rb
  spec/models/intervention/csv/harvester_spec.rb
  spec/requests/v1/questions/create_spec.rb
  spec/requests/v1/questions/third_party/create_spec.rb
  spec/requests/v1/sessions/clone_spec.rb
  spec/requests/v1/sessions/fetch_variables_spec.rb
  spec/services/v1/flow_service/next_question/branching_service_spec.rb
Labels: approved

#103 [CIAS30-3550] copy attachments during the copy process
  Gemfile
  Gemfile.lock
  app/models/concerns/clone/report_template.rb
  spec/factories/report_templates.rb
  spec/models/report_template_spec.rb
Labels: approved

#101 [CIAS30-3591] researcher can select delay of data clearance
  app/controllers/v1/interventions_controller.rb
  app/jobs/data_clear_jobs/inform_and_schedule.rb
  app/mailers/intervention_mailer/clear_data_mailer.rb
  app/views/intervention_mailer/clear_data_mailer/data_deleted.erb
  config/locales/en.yml
  spec/jobs/data_clear_jobs/inform_and_schedule_spec.rb
  spec/requests/v1/interventions/clear_user_data_spec.rb
Labels: approved

#83 [CIAS30-3531] Delete user data after intervention's closed
  .env.template
  Gemfile
  Gemfile.lock
  app/controllers/v1/interventions_controller.rb
  app/jobs/data_clear_jobs/clear_user_data.rb
  app/jobs/data_clear_jobs/inform_and_schedule.rb
  app/jobs/generate_user_session_reports_job.rb
  app/jobs/session_jobs/publish.rb
  app/mailers/intervention_mailer/clear_data_mailer.rb
  app/models/ability/admin.rb
  app/models/concerns/clone/intervention.rb
  app/models/intervention.rb
  app/models/notification.rb
  app/serializers/v1/intervention_serializer.rb
  app/serializers/v1/simple_intervention_serializer.rb
  app/views/intervention_mailer/clear_data_mailer/data_deleted.erb
  app/views/intervention_mailer/clear_data_mailer/inform.html.erb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20230808113423_add_flags_for_report_and_data_deletion_to_intervention.rb
  db/migrate/20230815122501_add_three_state_flags_to_interventions.rb
  db/schema.rb
  spec/factories/interventions.rb
  spec/fixtures/csv/example.csv
  spec/jobs/data_clear_jobs/clear_user_data_spec.rb
  spec/jobs/data_clear_jobs/inform_and_schedule_spec.rb
  spec/models/intervention_spec.rb
  spec/requests/v1/interventions/clear_user_data_spec.rb
Labels: approved

#102 [Cias30-3499] modify V1::GeneratedReports::ShareToThirdParty
  Gemfile
  Gemfile.lock
  app/services/api/documo/send_multiple_faxes.rb
  app/services/v1/generated_reports/share_to_third_party.rb
  spec/services/api/documo/send_multiple_faxes_spec.rb
  spec/services/v1/generated_reports/share_to_third_party_spec.rb
Labels: approved

#110 [CIAS30-3607] generate quarterly charts
  app/controllers/v1/organizations/charts_data/charts_data_controller.rb
  app/services/v1/chart_statistics/bar_chart.rb
  spec/requests/v1/charts/update_spec.rb
  spec/requests/v1/henry_ford/patient_details/verify_spec.rb
  spec/services/v1/chart_statistics/bar_chart/numeric_spec.rb
  spec/services/v1/chart_statistics/bar_chart/percentage_spec.rb
Labels: approved

#111 [CIAS30-3605] broadcast message on the correct stream
  app/channels/notification_channel.rb
Labels: approved

#113 [CIAS30-3134] load all the count values as a hash so you only need one call to the DB
  app/services/v1/chart_statistics/base.rb
Labels: approved

#114 [CIAS30-3617] Scheduled deletion job is started once again when the time of deletion come
  db/migrate/20230829180239_remove_constraint_about_user_id_from_chart_statistics.rb
  db/schema.rb
Labels: approved

#112 [CIAS30-3613] add migration to assign missing role
  db/migrate/20230829102615_assign_team_admin_role_to_team_admin.rb
Labels: approved

#105 [CIAS30-3574] add filtering interventions by whether they were starred
  app/models/intervention.rb
  spec/requests/v1/interventions/index_spec.rb
Labels: approved

#100 [CIAS30-3587] default order should take into account starred flag
  app/controllers/v1/interventions_controller.rb
  app/models/intervention.rb
  spec/requests/v1/interventions/index_spec.rb
Labels: approved

#97 [CIAS30-3573] add an ability to add a star to an intervention per user
  Gemfile.lock
  app/controllers/v1/interventions/stars_controller.rb
  app/controllers/v1/interventions_controller.rb
  app/models/intervention.rb
  app/models/star.rb
  app/models/user.rb
  app/serializers/v1/intervention_serializer.rb
  app/serializers/v1/simple_intervention_serializer.rb
  config/routes.rb
  db/migrate/20230821104043_create_stars_table.rb
  db/schema.rb
  spec/requests/v1/interventions/create_spec.rb
  spec/requests/v1/interventions/index_spec.rb
  spec/requests/v1/interventions/show_spec.rb
  spec/requests/v1/interventions/stars/create_spec.rb
  spec/requests/v1/interventions/stars/destroy_spec.rb
  spec/requests/v1/interventions/update_spec.rb
Labels: RfCR, approved

#109 [CIAS30-3567] Fix report template ids so they are correctly removed when changing the report template type
  app/models/concerns/clone/session.rb
  app/models/report_template.rb
  spec/requests/v1/report_templates/update_spec.rb
Labels: approved

#116 change place when information about navigators is
  app/serializers/v1/live_chat/interventions/live_chat_setup_serializer.rb
  app/serializers/v1/user_intervention_serializer.rb
  app/serializers/v1/user_session_serializer.rb
  spec/requests/v1/user_interventions/index_spec.rb
  spec/requests/v1/user_interventions/show_spec.rb
  spec/requests/v1/user_sessions/show_spec.rb
Labels: approved
