Repository Michigan-State-University/cias-api, pull requests merged in 2023-10, with the labels that each got.

#165 [CIAS30-3730] fix researcher cannot open preview when intervention belongs to the organiation
  app/models/user_intervention.rb
  app/models/user_session.rb
  spec/models/user_intervention_spec.rb
  spec/models/user_session_spec.rb
Labels: Maintenance, approved

#167 [CIAS30-3733] add missing attributes to serializer
  app/serializers/v1/predefined_participant_serializer.rb
  spec/requests/v1/interventions/predefined_participants/create_spec.rb
  spec/requests/v1/interventions/predefined_participants/index_spec.rb
  spec/requests/v1/interventions/predefined_participants/update_spec.rb
Labels: Maintenance, approved

#166 [CIAS30-3731] add order by after group_by
  app/models/intervention/csv/harvester.rb
  spec/models/intervention/csv/harvester_spec.rb
  spec/requests/v1/user_sessions/questions/previous_spec.rb
Labels: Maintenance, approved

#155 [CIAS30-3677] Add validation to the user session controller to check if a session can have multiple user_sessions for the same participant
  app/models/user_session.rb
  app/services/v1/user_sessions/base_service.rb
  db/migrate/20230929101211_add_partial_index_on_user_intervention.rb
  db/migrate/20230929103257_add_information_about_multiple_session.rb
  db/schema.rb
  spec/factories/user_sessions.rb
  spec/models/user_intervention_spec.rb
  spec/models/user_session_spec.rb
  spec/requests/v1/user_interventions/index_spec.rb
  spec/requests/v1/user_sessions/questions/index_spec.rb
  spec/services/v1/user_session_schedule_service_spec.rb
Labels: RfCR, Maintenance

#168 [CIAS30-3735] fix for "phone number is not being cleared"
  app/services/v1/intervention/predefined_participants/update_service.rb
  db/schema.rb
  spec/services/v1/intervention/predefined_participants/update_service_spec.rb
Labels: RfCR

#170 [CIAS30-3737] block sending welcome emails to predefined participants
  app/models/user.rb
  db/schema.rb
  spec/models/user_spec.rb
Labels: RfCR

#171 [CIAS30-3740] auto-finish block saving answers
  app/controllers/v1/user_sessions/answers_controller.rb
  config/locales/en.yml
  spec/requests/v1/answers/create_spec.rb
Labels: RfCR

#172 [CIAS30-3741] store information about an autogenerated emails
  app/models/user.rb
  app/serializers/v1/predefined_participant_serializer.rb
  app/services/v1/intervention/predefined_participants/create_service.rb
  db/migrate/20231005090624_add_email_autogenerated_flag_to_the_user_model.rb
  db/schema.rb
  spec/factories/users.rb
  spec/requests/v1/interventions/predefined_participants/create_spec.rb
  spec/requests/v1/interventions/predefined_participants/index_spec.rb
  spec/requests/v1/interventions/predefined_participants/update_spec.rb
  spec/services/v1/intervention/predefined_participants/create_service_spec.rb
  spec/services/v1/intervention/predefined_participants/update_service_spec.rb
Labels: approved

#173 [CIAS30-3738] more user-friendly error msg
  app/services/v1/intervention/predefined_participants/create_service.rb
  spec/services/v1/intervention/predefined_participants/create_service_spec.rb
Labels: RfCR

#177 [CIAS30-3747] block option to send SMSes to deactivated users
  app/services/v1/intervention/predefined_participants/send_invitation.rb
  config/locales/en.yml
  spec/services/v1/intervention/predefined_participants/send_invitation_spec.rb
Labels: approved

#176 [CIAS30-3719] do not send emails to participants
  app/controllers/v1/interventions_controller.rb
  app/jobs/data_clear_jobs/inform_and_schedule.rb
  app/mailers/intervention_mailer/clear_data_mailer.rb
  app/views/intervention_mailer/clear_data_mailer/data_deleted.erb
  app/views/intervention_mailer/clear_data_mailer/inform.html.erb
  config/locales/en.yml
  spec/jobs/data_clear_jobs/inform_and_schedule_spec.rb
  spec/requests/v1/interventions/clear_user_data_spec.rb
Labels: approved

#174 [CIAS30-3745] block access to deactivated users
  app/controllers/v1/organizations/invitations_controller.rb
  app/controllers/v1_controller.rb
  config/locales/en.yml
  spec/requests/v1/user_sessions/answers/create_spec.rb
  spec/requests/v1/user_sessions/questions/index_spec.rb
  spec/requests/v1/user_sessions/show_spec.rb
  spec/support/shared_examples/deactivated_account.rb
Labels: approved

#179 [CIAS30-3751] return up-to-data information after update
  app/services/v1/intervention/predefined_participants/update_service.rb
Labels: approved

#184 [CIAS30-3758] Add link to frontend repository in readme
  README.md
Labels: RfCR

#185 [CIAS30-3761] translate fax attributes
  app/models/concerns/translate/report_template.rb
  app/models/report_template.rb
  spec/models/report_template_spec.rb
Labels: RfCR

#187 [CIAS30-3757]add external name to clinic locations
  app/models/clinic_location.rb
  app/services/v1/henry_ford/verify_service.rb
  db/migrate/20231018071455_add_external_name_to_clinic_location.rb
  db/schema.rb
  lib/tasks/one_time_use/add_external_name_to_clinic_locations.rake
  spec/requests/v1/henry_ford/patient_details/verify_spec.rb
  spec/services/v1/henry_ford/verify_service_spec.rb
Labels: RfCR

#189 [CIAS30-3768] a new copy in an SMS message sent to previously defined participants
  config/locales/en.yml
Labels: RfCR

#181 Cias30 3618
  app/controllers/v1/twillo_message_controller.rb
  app/services/v1/henry_ford/verify_service.rb
  app/services/v1/sms/replay.rb
  config/routes.rb
  spec/requests/v1/twillo_message/create_spec.rb
  spec/services/v1/sms/replay_spec.rb
Labels: RfCR

#190 [CIAS30-3695] Handle RTL text in PDF reports
  app/views/report_templates/report_preview.html.erb
Labels: approved

#162 [CIAS30-3692] mailer wrapping
  app/jobs/interventions/invitation_job.rb
  app/jobs/send_fill_invitation/intervention_job.rb
  app/jobs/send_fill_invitation/session_job.rb
  app/jobs/send_new_report_notification_job.rb
  app/mailers/application_mailer.rb
  app/models/concerns/invitation_interface.rb
  app/models/intervention.rb
  app/models/invitation.rb
  app/models/question/finish.rb
  app/models/session.rb
  app/models/user.rb
  app/services/v1/generated_reports/share_to_participant.rb
  app/services/v1/generated_reports/share_to_third_party.rb
  app/services/v1/users/sms_tokens/send.rb
  app/services/v1/users/verifications/create.rb
  config/application.rb
  config/locales/ar.yml
  config/locales/en.yml
  db/migrate/20231003060946_add_default_language_code_to_user.rb
  db/schema.rb
  lib/tasks/scheduler.rake
  spec/jobs/interventions/invitation_job_spec.rb
  spec/models/invitation_spec.rb
  spec/models/question/finish_spec.rb
  spec/rails_helper.rb
  spec/services/v1/generated_reports/share_to_participant_spec.rb
  spec/services/v1/generated_reports/share_to_third_party_spec.rb
  spec/services/v1/user_session_schedule_service_spec.rb
  spec/support/mailer_helpers.rb
Labels: Improvements, Comment, BLOCKED
