Repository Michigan-State-University/cias-api, pull requests merged in 2023-07, with the labels that each got.

#37 [CIAS30-3486] Update repo links in documentation
  .github/ISSUE_TEMPLATE/bug_report.md
  CONTRIBUTING.md
  README.md
Labels: RfCR

#48 [CIAS30-3505]: Adjust the error message, so it will not only mention the T&C and Privacy Policy, but also a First/Last name
  config/locales/en.yml
Labels: approved

#46 CIAS30-3195
  app/models/chart.rb
  app/models/concerns/clone/chart.rb
  app/services/v1/charts/create.rb
  spec/requests/v1/charts/clone_spec.rb
  spec/requests/v1/charts/create_spec.rb
Labels: approved

#44 CIAS30-3479: Invite new users when sharing externally intervention or question group externally
  app/jobs/clone_jobs/intervention.rb
  app/mailers/clone_mailer.rb
  app/models/concerns/clone.rb
  app/services/v1/question_group/share_externally_service.rb
  app/views/clone_mailer/cloned_intervention_activate.html.erb
  app/views/clone_mailer/cloned_question_group_activate.erb
  app/views/intervention_mailer/share_externally_and_registration.html.erb
  app/views/intervention_mailer/share_question_group_and_registration.html.erb
  config/locales/en.yml
  spec/jobs/clone_jobs/intervention_spec.rb
  spec/services/v1/question_group/share_externally_service_spec.rb
Labels: approved

#51 Cias30 3384
  app/jobs/clone_jobs/session.rb
  app/models/concerns/clone/session.rb
  spec/jobs/clone_jobs/session_spec.rb
  spec/jobs/duplicate_jobs/session_spec.rb
Labels: approved

#49 [Cias30-3502] Return hfhs_patient_detail when fetching question in user session
  app/controllers/concerns/auth/default.rb
  app/controllers/concerns/exception_handler.rb
  app/controllers/v1/auth/sessions_controller.rb
  app/controllers/v1/henry_ford/clinic_locations_controller.rb
  app/controllers/v1/henry_ford/patient_details_controller.rb
  app/controllers/v1/interventions_controller.rb
  app/controllers/v1/user_sessions/questions_controller.rb
  app/controllers/v1/users_controller.rb
  app/exceptions/complex_exception.rb
  app/models/clinic_location.rb
  app/models/collaborator.rb
  app/models/concerns/clone.rb
  app/models/intervention.rb
  app/models/intervention/csv/harvester.rb
  app/models/intervention_location.rb
  app/models/user.rb
  app/serializers/v1/clinic_location_serializer.rb
  app/serializers/v1/intervention_serializer.rb
  app/serializers/v1/simple_intervention_serializer.rb
  app/serializers/v1/user_serializer.rb
  app/services/v1/henry_ford/verify_service.rb
  app/services/v1/intervention/update.rb
  app/services/v1/question/response.rb
  app/services/v1/question_group/share_externally_service.rb
  app/services/v1/users/terms/confirm.rb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20230718064619_create_clinic_locations.rb
  db/migrate/20230718065226_create_intervention_locations.rb
  db/migrate/20230719115208_dump_locations.rb
  db/schema.rb
  db/seeds.rb
  lib/tasks/one_time_use/dump_clinic_locations.rake
  spec/factories/clinic_location.rb
  spec/factories/intervention_location.rb
  spec/fixtures/integrations/henry_ford/appointments.json
  spec/models/clinic_location_spec.rb
  spec/models/intervention/csv/harvester_spec.rb
  spec/models/intervention_location_spec.rb
  spec/models/intervention_spec.rb
  spec/requests/v1/auth/sessions/create_spec.rb
  spec/requests/v1/health_systems/show_spec.rb
  spec/requests/v1/henry_ford/clinic_locations/index_spec.rb
  spec/requests/v1/henry_ford/patient_details/verify_spec.rb
  spec/requests/v1/interventions/collaborators/create_spec.rb
  spec/requests/v1/interventions/update_spec.rb
  spec/requests/v1/organizations/show_spec.rb
  spec/requests/v1/teams/index_spec.rb
  spec/requests/v1/user_sessions/questions/index_spec.rb
  spec/requests/v1/user_sessions/questions/previous_spec.rb
  spec/requests/v1/users/confirm_terms_spec.rb
  spec/requests/v1/users/send_sms_token_spec.rb
  spec/services/v1/henry_ford/verify_service_spec.rb
  spec/services/v1/live_chat/interventions/navigators/send_messages_service_spec.rb
  spec/services/v1/question_group/share_externally_service_spec.rb
Labels: Henry Ford integration
