Repository Michigan-State-University/cias-api, pull requests merged in 2024-01, with the labels that each got.

#229 CIAS30-3877 Use reflection service while fetching previous question
  app/services/v1/flow_service/reflection_service.rb
  app/services/v1/user_sessions/previous_question_service.rb
  spec/requests/v1/user_sessions/questions/previous_spec.rb
Labels: approved

#230 CIAS30-3879 Add missing values to reflection block, while copying que…
  app/jobs/duplicate_jobs/session.rb
  app/models/concerns/clone/question_group.rb
  app/models/concerns/clone/session.rb
  spec/jobs/clone_jobs/session_spec.rb
Labels: approved

#232 [CIAS30-3867] Variables should be case-insensitive
  Gemfile
  Gemfile.lock
  app/services/v1/question/update.rb
  config/locales/en.yml
  spec/requests/v1/questions/update_spec.rb
Labels: RfCR, approved

#237 [CIAS30-3891] set blocked to false if user has assigned predefined participant role
  app/serializers/v1/user_intervention_serializer.rb
  spec/requests/v1/user_interventions/show_spec.rb
Labels: RfCR
